// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

public final class ChatProtos {
  private ChatProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_game_proto_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_game_proto_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_game_proto_SendMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_game_proto_SendMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_game_proto_ReceiveMessageNotification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_game_proto_ReceiveMessageNotification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nchat.proto\022\025com.sirius.game.proto\"\334\001\n\007" +
      "Message\0220\n\004type\030\001 \001(\0162\".com.sirius.game." +
      "proto.MessageType\022A\n\014send_request\030\002 \001(\0132" +
      ").com.sirius.game.proto.SendMessageReque" +
      "stH\000\022Q\n\024receive_notification\030\003 \001(\01321.com" +
      ".sirius.game.proto.ReceiveMessageNotific" +
      "ationH\000B\t\n\007payload\"R\n\022SendMessageRequest" +
      "\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\017\n\007content\030\003 " +
      "\001(\t\022\021\n\ttimestamp\030\004 \001(\003\"n\n\032ReceiveMessage" +
      "Notification\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\017" +
      "\n\007content\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003\022\022\n\nme" +
      "ssage_id\030\005 \001(\t*F\n\013MessageType\022\013\n\007UNKNOWN" +
      "\020\000\022\020\n\014SEND_REQUEST\020\001\022\030\n\024RECEIVE_NOTIFICA" +
      "TION\020\002B%\n\025com.sirius.game.protoB\nChatPro" +
      "tosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sirius_game_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sirius_game_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_game_proto_Message_descriptor,
        new java.lang.String[] { "Type", "SendRequest", "ReceiveNotification", "Payload", });
    internal_static_com_sirius_game_proto_SendMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sirius_game_proto_SendMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_game_proto_SendMessageRequest_descriptor,
        new java.lang.String[] { "From", "To", "Content", "Timestamp", });
    internal_static_com_sirius_game_proto_ReceiveMessageNotification_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sirius_game_proto_ReceiveMessageNotification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_game_proto_ReceiveMessageNotification_descriptor,
        new java.lang.String[] { "From", "To", "Content", "Timestamp", "MessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
