// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

/**
 * <pre>
 * 统一消息类型
 * </pre>
 *
 * Protobuf type {@code com.sirius.game.proto.GameMessage}
 */
public final class GameMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.sirius.game.proto.GameMessage)
    GameMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GameMessage.newBuilder() to construct.
  private GameMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GameMessage() {
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GameMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sirius.game.proto.GameProtos.internal_static_com_sirius_game_proto_GameMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sirius.game.proto.GameProtos.internal_static_com_sirius_game_proto_GameMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sirius.game.proto.GameMessage.class, com.sirius.game.proto.GameMessage.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    CS_LOGIN(1001),
    SC_LOGIN_RESULT(1002),
    CS_SEND_MESSAGE(2001),
    SC_RECEIVE_MESSAGE(2002),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 1001: return CS_LOGIN;
        case 1002: return SC_LOGIN_RESULT;
        case 2001: return CS_SEND_MESSAGE;
        case 2002: return SC_RECEIVE_MESSAGE;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <pre>
   * 消息类型标识符
   * </pre>
   *
   * <code>.com.sirius.game.proto.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 消息类型标识符
   * </pre>
   *
   * <code>.com.sirius.game.proto.MessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.sirius.game.proto.MessageType getType() {
    com.sirius.game.proto.MessageType result = com.sirius.game.proto.MessageType.forNumber(type_);
    return result == null ? com.sirius.game.proto.MessageType.UNRECOGNIZED : result;
  }

  public static final int CS_LOGIN_FIELD_NUMBER = 1001;
  /**
   * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
   * @return Whether the csLogin field is set.
   */
  @java.lang.Override
  public boolean hasCsLogin() {
    return payloadCase_ == 1001;
  }
  /**
   * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
   * @return The csLogin.
   */
  @java.lang.Override
  public com.sirius.game.proto.CSLogin getCsLogin() {
    if (payloadCase_ == 1001) {
       return (com.sirius.game.proto.CSLogin) payload_;
    }
    return com.sirius.game.proto.CSLogin.getDefaultInstance();
  }
  /**
   * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
   */
  @java.lang.Override
  public com.sirius.game.proto.CSLoginOrBuilder getCsLoginOrBuilder() {
    if (payloadCase_ == 1001) {
       return (com.sirius.game.proto.CSLogin) payload_;
    }
    return com.sirius.game.proto.CSLogin.getDefaultInstance();
  }

  public static final int SC_LOGIN_RESULT_FIELD_NUMBER = 1002;
  /**
   * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
   * @return Whether the scLoginResult field is set.
   */
  @java.lang.Override
  public boolean hasScLoginResult() {
    return payloadCase_ == 1002;
  }
  /**
   * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
   * @return The scLoginResult.
   */
  @java.lang.Override
  public com.sirius.game.proto.SCLoginResult getScLoginResult() {
    if (payloadCase_ == 1002) {
       return (com.sirius.game.proto.SCLoginResult) payload_;
    }
    return com.sirius.game.proto.SCLoginResult.getDefaultInstance();
  }
  /**
   * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
   */
  @java.lang.Override
  public com.sirius.game.proto.SCLoginResultOrBuilder getScLoginResultOrBuilder() {
    if (payloadCase_ == 1002) {
       return (com.sirius.game.proto.SCLoginResult) payload_;
    }
    return com.sirius.game.proto.SCLoginResult.getDefaultInstance();
  }

  public static final int CS_SEND_MESSAGE_FIELD_NUMBER = 2001;
  /**
   * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
   * @return Whether the csSendMessage field is set.
   */
  @java.lang.Override
  public boolean hasCsSendMessage() {
    return payloadCase_ == 2001;
  }
  /**
   * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
   * @return The csSendMessage.
   */
  @java.lang.Override
  public com.sirius.game.proto.CSSendMessage getCsSendMessage() {
    if (payloadCase_ == 2001) {
       return (com.sirius.game.proto.CSSendMessage) payload_;
    }
    return com.sirius.game.proto.CSSendMessage.getDefaultInstance();
  }
  /**
   * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
   */
  @java.lang.Override
  public com.sirius.game.proto.CSSendMessageOrBuilder getCsSendMessageOrBuilder() {
    if (payloadCase_ == 2001) {
       return (com.sirius.game.proto.CSSendMessage) payload_;
    }
    return com.sirius.game.proto.CSSendMessage.getDefaultInstance();
  }

  public static final int SC_RECEIVE_MESSAGE_FIELD_NUMBER = 2002;
  /**
   * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
   * @return Whether the scReceiveMessage field is set.
   */
  @java.lang.Override
  public boolean hasScReceiveMessage() {
    return payloadCase_ == 2002;
  }
  /**
   * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
   * @return The scReceiveMessage.
   */
  @java.lang.Override
  public com.sirius.game.proto.SCReceiveMessage getScReceiveMessage() {
    if (payloadCase_ == 2002) {
       return (com.sirius.game.proto.SCReceiveMessage) payload_;
    }
    return com.sirius.game.proto.SCReceiveMessage.getDefaultInstance();
  }
  /**
   * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
   */
  @java.lang.Override
  public com.sirius.game.proto.SCReceiveMessageOrBuilder getScReceiveMessageOrBuilder() {
    if (payloadCase_ == 2002) {
       return (com.sirius.game.proto.SCReceiveMessage) payload_;
    }
    return com.sirius.game.proto.SCReceiveMessage.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.sirius.game.proto.MessageType.UNKNOWN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (payloadCase_ == 1001) {
      output.writeMessage(1001, (com.sirius.game.proto.CSLogin) payload_);
    }
    if (payloadCase_ == 1002) {
      output.writeMessage(1002, (com.sirius.game.proto.SCLoginResult) payload_);
    }
    if (payloadCase_ == 2001) {
      output.writeMessage(2001, (com.sirius.game.proto.CSSendMessage) payload_);
    }
    if (payloadCase_ == 2002) {
      output.writeMessage(2002, (com.sirius.game.proto.SCReceiveMessage) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.sirius.game.proto.MessageType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (payloadCase_ == 1001) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1001, (com.sirius.game.proto.CSLogin) payload_);
    }
    if (payloadCase_ == 1002) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1002, (com.sirius.game.proto.SCLoginResult) payload_);
    }
    if (payloadCase_ == 2001) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2001, (com.sirius.game.proto.CSSendMessage) payload_);
    }
    if (payloadCase_ == 2002) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2002, (com.sirius.game.proto.SCReceiveMessage) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sirius.game.proto.GameMessage)) {
      return super.equals(obj);
    }
    com.sirius.game.proto.GameMessage other = (com.sirius.game.proto.GameMessage) obj;

    if (type_ != other.type_) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 1001:
        if (!getCsLogin()
            .equals(other.getCsLogin())) return false;
        break;
      case 1002:
        if (!getScLoginResult()
            .equals(other.getScLoginResult())) return false;
        break;
      case 2001:
        if (!getCsSendMessage()
            .equals(other.getCsSendMessage())) return false;
        break;
      case 2002:
        if (!getScReceiveMessage()
            .equals(other.getScReceiveMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (payloadCase_) {
      case 1001:
        hash = (37 * hash) + CS_LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + getCsLogin().hashCode();
        break;
      case 1002:
        hash = (37 * hash) + SC_LOGIN_RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getScLoginResult().hashCode();
        break;
      case 2001:
        hash = (37 * hash) + CS_SEND_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getCsSendMessage().hashCode();
        break;
      case 2002:
        hash = (37 * hash) + SC_RECEIVE_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getScReceiveMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sirius.game.proto.GameMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sirius.game.proto.GameMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sirius.game.proto.GameMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sirius.game.proto.GameMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sirius.game.proto.GameMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 统一消息类型
   * </pre>
   *
   * Protobuf type {@code com.sirius.game.proto.GameMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.sirius.game.proto.GameMessage)
      com.sirius.game.proto.GameMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sirius.game.proto.GameProtos.internal_static_com_sirius_game_proto_GameMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sirius.game.proto.GameProtos.internal_static_com_sirius_game_proto_GameMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sirius.game.proto.GameMessage.class, com.sirius.game.proto.GameMessage.Builder.class);
    }

    // Construct using com.sirius.game.proto.GameMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      if (csLoginBuilder_ != null) {
        csLoginBuilder_.clear();
      }
      if (scLoginResultBuilder_ != null) {
        scLoginResultBuilder_.clear();
      }
      if (csSendMessageBuilder_ != null) {
        csSendMessageBuilder_.clear();
      }
      if (scReceiveMessageBuilder_ != null) {
        scReceiveMessageBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sirius.game.proto.GameProtos.internal_static_com_sirius_game_proto_GameMessage_descriptor;
    }

    @java.lang.Override
    public com.sirius.game.proto.GameMessage getDefaultInstanceForType() {
      return com.sirius.game.proto.GameMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.sirius.game.proto.GameMessage build() {
      com.sirius.game.proto.GameMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sirius.game.proto.GameMessage buildPartial() {
      com.sirius.game.proto.GameMessage result = new com.sirius.game.proto.GameMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sirius.game.proto.GameMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
    }

    private void buildPartialOneofs(com.sirius.game.proto.GameMessage result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 1001 &&
          csLoginBuilder_ != null) {
        result.payload_ = csLoginBuilder_.build();
      }
      if (payloadCase_ == 1002 &&
          scLoginResultBuilder_ != null) {
        result.payload_ = scLoginResultBuilder_.build();
      }
      if (payloadCase_ == 2001 &&
          csSendMessageBuilder_ != null) {
        result.payload_ = csSendMessageBuilder_.build();
      }
      if (payloadCase_ == 2002 &&
          scReceiveMessageBuilder_ != null) {
        result.payload_ = scReceiveMessageBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sirius.game.proto.GameMessage) {
        return mergeFrom((com.sirius.game.proto.GameMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sirius.game.proto.GameMessage other) {
      if (other == com.sirius.game.proto.GameMessage.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getPayloadCase()) {
        case CS_LOGIN: {
          mergeCsLogin(other.getCsLogin());
          break;
        }
        case SC_LOGIN_RESULT: {
          mergeScLoginResult(other.getScLoginResult());
          break;
        }
        case CS_SEND_MESSAGE: {
          mergeCsSendMessage(other.getCsSendMessage());
          break;
        }
        case SC_RECEIVE_MESSAGE: {
          mergeScReceiveMessage(other.getScReceiveMessage());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 8010: {
              input.readMessage(
                  getCsLoginFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1001;
              break;
            } // case 8010
            case 8018: {
              input.readMessage(
                  getScLoginResultFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 1002;
              break;
            } // case 8018
            case 16010: {
              input.readMessage(
                  getCsSendMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2001;
              break;
            } // case 16010
            case 16018: {
              input.readMessage(
                  getScReceiveMessageFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2002;
              break;
            } // case 16018
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.sirius.game.proto.MessageType getType() {
      com.sirius.game.proto.MessageType result = com.sirius.game.proto.MessageType.forNumber(type_);
      return result == null ? com.sirius.game.proto.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.sirius.game.proto.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.CSLogin, com.sirius.game.proto.CSLogin.Builder, com.sirius.game.proto.CSLoginOrBuilder> csLoginBuilder_;
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     * @return Whether the csLogin field is set.
     */
    @java.lang.Override
    public boolean hasCsLogin() {
      return payloadCase_ == 1001;
    }
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     * @return The csLogin.
     */
    @java.lang.Override
    public com.sirius.game.proto.CSLogin getCsLogin() {
      if (csLoginBuilder_ == null) {
        if (payloadCase_ == 1001) {
          return (com.sirius.game.proto.CSLogin) payload_;
        }
        return com.sirius.game.proto.CSLogin.getDefaultInstance();
      } else {
        if (payloadCase_ == 1001) {
          return csLoginBuilder_.getMessage();
        }
        return com.sirius.game.proto.CSLogin.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     */
    public Builder setCsLogin(com.sirius.game.proto.CSLogin value) {
      if (csLoginBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        csLoginBuilder_.setMessage(value);
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     */
    public Builder setCsLogin(
        com.sirius.game.proto.CSLogin.Builder builderForValue) {
      if (csLoginBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        csLoginBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     */
    public Builder mergeCsLogin(com.sirius.game.proto.CSLogin value) {
      if (csLoginBuilder_ == null) {
        if (payloadCase_ == 1001 &&
            payload_ != com.sirius.game.proto.CSLogin.getDefaultInstance()) {
          payload_ = com.sirius.game.proto.CSLogin.newBuilder((com.sirius.game.proto.CSLogin) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1001) {
          csLoginBuilder_.mergeFrom(value);
        } else {
          csLoginBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1001;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     */
    public Builder clearCsLogin() {
      if (csLoginBuilder_ == null) {
        if (payloadCase_ == 1001) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1001) {
          payloadCase_ = 0;
          payload_ = null;
        }
        csLoginBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     */
    public com.sirius.game.proto.CSLogin.Builder getCsLoginBuilder() {
      return getCsLoginFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     */
    @java.lang.Override
    public com.sirius.game.proto.CSLoginOrBuilder getCsLoginOrBuilder() {
      if ((payloadCase_ == 1001) && (csLoginBuilder_ != null)) {
        return csLoginBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1001) {
          return (com.sirius.game.proto.CSLogin) payload_;
        }
        return com.sirius.game.proto.CSLogin.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.CSLogin, com.sirius.game.proto.CSLogin.Builder, com.sirius.game.proto.CSLoginOrBuilder> 
        getCsLoginFieldBuilder() {
      if (csLoginBuilder_ == null) {
        if (!(payloadCase_ == 1001)) {
          payload_ = com.sirius.game.proto.CSLogin.getDefaultInstance();
        }
        csLoginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sirius.game.proto.CSLogin, com.sirius.game.proto.CSLogin.Builder, com.sirius.game.proto.CSLoginOrBuilder>(
                (com.sirius.game.proto.CSLogin) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1001;
      onChanged();
      return csLoginBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.SCLoginResult, com.sirius.game.proto.SCLoginResult.Builder, com.sirius.game.proto.SCLoginResultOrBuilder> scLoginResultBuilder_;
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     * @return Whether the scLoginResult field is set.
     */
    @java.lang.Override
    public boolean hasScLoginResult() {
      return payloadCase_ == 1002;
    }
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     * @return The scLoginResult.
     */
    @java.lang.Override
    public com.sirius.game.proto.SCLoginResult getScLoginResult() {
      if (scLoginResultBuilder_ == null) {
        if (payloadCase_ == 1002) {
          return (com.sirius.game.proto.SCLoginResult) payload_;
        }
        return com.sirius.game.proto.SCLoginResult.getDefaultInstance();
      } else {
        if (payloadCase_ == 1002) {
          return scLoginResultBuilder_.getMessage();
        }
        return com.sirius.game.proto.SCLoginResult.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     */
    public Builder setScLoginResult(com.sirius.game.proto.SCLoginResult value) {
      if (scLoginResultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        scLoginResultBuilder_.setMessage(value);
      }
      payloadCase_ = 1002;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     */
    public Builder setScLoginResult(
        com.sirius.game.proto.SCLoginResult.Builder builderForValue) {
      if (scLoginResultBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        scLoginResultBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 1002;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     */
    public Builder mergeScLoginResult(com.sirius.game.proto.SCLoginResult value) {
      if (scLoginResultBuilder_ == null) {
        if (payloadCase_ == 1002 &&
            payload_ != com.sirius.game.proto.SCLoginResult.getDefaultInstance()) {
          payload_ = com.sirius.game.proto.SCLoginResult.newBuilder((com.sirius.game.proto.SCLoginResult) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 1002) {
          scLoginResultBuilder_.mergeFrom(value);
        } else {
          scLoginResultBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 1002;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     */
    public Builder clearScLoginResult() {
      if (scLoginResultBuilder_ == null) {
        if (payloadCase_ == 1002) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 1002) {
          payloadCase_ = 0;
          payload_ = null;
        }
        scLoginResultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     */
    public com.sirius.game.proto.SCLoginResult.Builder getScLoginResultBuilder() {
      return getScLoginResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     */
    @java.lang.Override
    public com.sirius.game.proto.SCLoginResultOrBuilder getScLoginResultOrBuilder() {
      if ((payloadCase_ == 1002) && (scLoginResultBuilder_ != null)) {
        return scLoginResultBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 1002) {
          return (com.sirius.game.proto.SCLoginResult) payload_;
        }
        return com.sirius.game.proto.SCLoginResult.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.SCLoginResult, com.sirius.game.proto.SCLoginResult.Builder, com.sirius.game.proto.SCLoginResultOrBuilder> 
        getScLoginResultFieldBuilder() {
      if (scLoginResultBuilder_ == null) {
        if (!(payloadCase_ == 1002)) {
          payload_ = com.sirius.game.proto.SCLoginResult.getDefaultInstance();
        }
        scLoginResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sirius.game.proto.SCLoginResult, com.sirius.game.proto.SCLoginResult.Builder, com.sirius.game.proto.SCLoginResultOrBuilder>(
                (com.sirius.game.proto.SCLoginResult) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 1002;
      onChanged();
      return scLoginResultBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.CSSendMessage, com.sirius.game.proto.CSSendMessage.Builder, com.sirius.game.proto.CSSendMessageOrBuilder> csSendMessageBuilder_;
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     * @return Whether the csSendMessage field is set.
     */
    @java.lang.Override
    public boolean hasCsSendMessage() {
      return payloadCase_ == 2001;
    }
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     * @return The csSendMessage.
     */
    @java.lang.Override
    public com.sirius.game.proto.CSSendMessage getCsSendMessage() {
      if (csSendMessageBuilder_ == null) {
        if (payloadCase_ == 2001) {
          return (com.sirius.game.proto.CSSendMessage) payload_;
        }
        return com.sirius.game.proto.CSSendMessage.getDefaultInstance();
      } else {
        if (payloadCase_ == 2001) {
          return csSendMessageBuilder_.getMessage();
        }
        return com.sirius.game.proto.CSSendMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     */
    public Builder setCsSendMessage(com.sirius.game.proto.CSSendMessage value) {
      if (csSendMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        csSendMessageBuilder_.setMessage(value);
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     */
    public Builder setCsSendMessage(
        com.sirius.game.proto.CSSendMessage.Builder builderForValue) {
      if (csSendMessageBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        csSendMessageBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     */
    public Builder mergeCsSendMessage(com.sirius.game.proto.CSSendMessage value) {
      if (csSendMessageBuilder_ == null) {
        if (payloadCase_ == 2001 &&
            payload_ != com.sirius.game.proto.CSSendMessage.getDefaultInstance()) {
          payload_ = com.sirius.game.proto.CSSendMessage.newBuilder((com.sirius.game.proto.CSSendMessage) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2001) {
          csSendMessageBuilder_.mergeFrom(value);
        } else {
          csSendMessageBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2001;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     */
    public Builder clearCsSendMessage() {
      if (csSendMessageBuilder_ == null) {
        if (payloadCase_ == 2001) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2001) {
          payloadCase_ = 0;
          payload_ = null;
        }
        csSendMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     */
    public com.sirius.game.proto.CSSendMessage.Builder getCsSendMessageBuilder() {
      return getCsSendMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     */
    @java.lang.Override
    public com.sirius.game.proto.CSSendMessageOrBuilder getCsSendMessageOrBuilder() {
      if ((payloadCase_ == 2001) && (csSendMessageBuilder_ != null)) {
        return csSendMessageBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2001) {
          return (com.sirius.game.proto.CSSendMessage) payload_;
        }
        return com.sirius.game.proto.CSSendMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.CSSendMessage, com.sirius.game.proto.CSSendMessage.Builder, com.sirius.game.proto.CSSendMessageOrBuilder> 
        getCsSendMessageFieldBuilder() {
      if (csSendMessageBuilder_ == null) {
        if (!(payloadCase_ == 2001)) {
          payload_ = com.sirius.game.proto.CSSendMessage.getDefaultInstance();
        }
        csSendMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sirius.game.proto.CSSendMessage, com.sirius.game.proto.CSSendMessage.Builder, com.sirius.game.proto.CSSendMessageOrBuilder>(
                (com.sirius.game.proto.CSSendMessage) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2001;
      onChanged();
      return csSendMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.SCReceiveMessage, com.sirius.game.proto.SCReceiveMessage.Builder, com.sirius.game.proto.SCReceiveMessageOrBuilder> scReceiveMessageBuilder_;
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     * @return Whether the scReceiveMessage field is set.
     */
    @java.lang.Override
    public boolean hasScReceiveMessage() {
      return payloadCase_ == 2002;
    }
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     * @return The scReceiveMessage.
     */
    @java.lang.Override
    public com.sirius.game.proto.SCReceiveMessage getScReceiveMessage() {
      if (scReceiveMessageBuilder_ == null) {
        if (payloadCase_ == 2002) {
          return (com.sirius.game.proto.SCReceiveMessage) payload_;
        }
        return com.sirius.game.proto.SCReceiveMessage.getDefaultInstance();
      } else {
        if (payloadCase_ == 2002) {
          return scReceiveMessageBuilder_.getMessage();
        }
        return com.sirius.game.proto.SCReceiveMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     */
    public Builder setScReceiveMessage(com.sirius.game.proto.SCReceiveMessage value) {
      if (scReceiveMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        scReceiveMessageBuilder_.setMessage(value);
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     */
    public Builder setScReceiveMessage(
        com.sirius.game.proto.SCReceiveMessage.Builder builderForValue) {
      if (scReceiveMessageBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        scReceiveMessageBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     */
    public Builder mergeScReceiveMessage(com.sirius.game.proto.SCReceiveMessage value) {
      if (scReceiveMessageBuilder_ == null) {
        if (payloadCase_ == 2002 &&
            payload_ != com.sirius.game.proto.SCReceiveMessage.getDefaultInstance()) {
          payload_ = com.sirius.game.proto.SCReceiveMessage.newBuilder((com.sirius.game.proto.SCReceiveMessage) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2002) {
          scReceiveMessageBuilder_.mergeFrom(value);
        } else {
          scReceiveMessageBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2002;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     */
    public Builder clearScReceiveMessage() {
      if (scReceiveMessageBuilder_ == null) {
        if (payloadCase_ == 2002) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2002) {
          payloadCase_ = 0;
          payload_ = null;
        }
        scReceiveMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     */
    public com.sirius.game.proto.SCReceiveMessage.Builder getScReceiveMessageBuilder() {
      return getScReceiveMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     */
    @java.lang.Override
    public com.sirius.game.proto.SCReceiveMessageOrBuilder getScReceiveMessageOrBuilder() {
      if ((payloadCase_ == 2002) && (scReceiveMessageBuilder_ != null)) {
        return scReceiveMessageBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2002) {
          return (com.sirius.game.proto.SCReceiveMessage) payload_;
        }
        return com.sirius.game.proto.SCReceiveMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.SCReceiveMessage, com.sirius.game.proto.SCReceiveMessage.Builder, com.sirius.game.proto.SCReceiveMessageOrBuilder> 
        getScReceiveMessageFieldBuilder() {
      if (scReceiveMessageBuilder_ == null) {
        if (!(payloadCase_ == 2002)) {
          payload_ = com.sirius.game.proto.SCReceiveMessage.getDefaultInstance();
        }
        scReceiveMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sirius.game.proto.SCReceiveMessage, com.sirius.game.proto.SCReceiveMessage.Builder, com.sirius.game.proto.SCReceiveMessageOrBuilder>(
                (com.sirius.game.proto.SCReceiveMessage) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2002;
      onChanged();
      return scReceiveMessageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.sirius.game.proto.GameMessage)
  }

  // @@protoc_insertion_point(class_scope:com.sirius.game.proto.GameMessage)
  private static final com.sirius.game.proto.GameMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sirius.game.proto.GameMessage();
  }

  public static com.sirius.game.proto.GameMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GameMessage>
      PARSER = new com.google.protobuf.AbstractParser<GameMessage>() {
    @java.lang.Override
    public GameMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GameMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GameMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sirius.game.proto.GameMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

