// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

public final class GameProtos {
  private GameProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_game_proto_GameMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_game_proto_GameMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_game_proto_CSLogin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_game_proto_CSLogin_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_game_proto_SCLoginResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_game_proto_SCLoginResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_game_proto_CSSendMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_game_proto_CSSendMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sirius_game_proto_SCReceiveMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sirius_game_proto_SCReceiveMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\022\025com.sirius.game.proto\"\313\002\n\013" +
      "GameMessage\0220\n\004type\030\001 \001(\0162\".com.sirius.g" +
      "ame.proto.MessageType\0223\n\010cs_login\030\351\007 \001(\013" +
      "2\036.com.sirius.game.proto.CSLoginH\000\022@\n\017sc" +
      "_login_result\030\352\007 \001(\0132$.com.sirius.game.p" +
      "roto.SCLoginResultH\000\022@\n\017cs_send_message\030" +
      "\321\017 \001(\0132$.com.sirius.game.proto.CSSendMes" +
      "sageH\000\022F\n\022sc_receive_message\030\322\017 \001(\0132\'.co" +
      "m.sirius.game.proto.SCReceiveMessageH\000B\t" +
      "\n\007payload\"@\n\007CSLogin\022\020\n\010username\030\001 \001(\t\022\020" +
      "\n\010password\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\"l\n\rS" +
      "CLoginResult\022\017\n\007success\030\001 \001(\010\022\017\n\007message" +
      "\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\t\022\025\n\rsession_token" +
      "\030\004 \001(\t\022\021\n\ttimestamp\030\005 \001(\003\"M\n\rCSSendMessa" +
      "ge\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\017\n\007content\030" +
      "\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003\"d\n\020SCReceiveMes" +
      "sage\022\014\n\004from\030\001 \001(\t\022\n\n\002to\030\002 \001(\t\022\017\n\007conten" +
      "t\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\003\022\022\n\nmessage_id" +
      "\030\005 \001(\t*n\n\013MessageType\022\013\n\007UNKNOWN\020\000\022\r\n\010CS" +
      "_LOGIN\020\351\007\022\024\n\017SC_LOGIN_RESULT\020\352\007\022\024\n\017CS_SE" +
      "ND_MESSAGE\020\321\017\022\027\n\022SC_RECEIVE_MESSAGE\020\322\017B%" +
      "\n\025com.sirius.game.protoB\nGameProtosP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sirius_game_proto_GameMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sirius_game_proto_GameMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_game_proto_GameMessage_descriptor,
        new java.lang.String[] { "Type", "CsLogin", "ScLoginResult", "CsSendMessage", "ScReceiveMessage", "Payload", });
    internal_static_com_sirius_game_proto_CSLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sirius_game_proto_CSLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_game_proto_CSLogin_descriptor,
        new java.lang.String[] { "Username", "Password", "Timestamp", });
    internal_static_com_sirius_game_proto_SCLoginResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_sirius_game_proto_SCLoginResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_game_proto_SCLoginResult_descriptor,
        new java.lang.String[] { "Success", "Message", "UserId", "SessionToken", "Timestamp", });
    internal_static_com_sirius_game_proto_CSSendMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_sirius_game_proto_CSSendMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_game_proto_CSSendMessage_descriptor,
        new java.lang.String[] { "From", "To", "Content", "Timestamp", });
    internal_static_com_sirius_game_proto_SCReceiveMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_sirius_game_proto_SCReceiveMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sirius_game_proto_SCReceiveMessage_descriptor,
        new java.lang.String[] { "From", "To", "Content", "Timestamp", "MessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
