// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

public interface GameMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sirius.game.proto.GameMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息类型标识符
   * </pre>
   *
   * <code>.com.sirius.game.proto.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * 消息类型标识符
   * </pre>
   *
   * <code>.com.sirius.game.proto.MessageType type = 1;</code>
   * @return The type.
   */
  com.sirius.game.proto.MessageType getType();

  /**
   * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
   * @return Whether the csLogin field is set.
   */
  boolean hasCsLogin();
  /**
   * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
   * @return The csLogin.
   */
  com.sirius.game.proto.CSLogin getCsLogin();
  /**
   * <code>.com.sirius.game.proto.CSLogin cs_login = 1001;</code>
   */
  com.sirius.game.proto.CSLoginOrBuilder getCsLoginOrBuilder();

  /**
   * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
   * @return Whether the scLoginResult field is set.
   */
  boolean hasScLoginResult();
  /**
   * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
   * @return The scLoginResult.
   */
  com.sirius.game.proto.SCLoginResult getScLoginResult();
  /**
   * <code>.com.sirius.game.proto.SCLoginResult sc_login_result = 1002;</code>
   */
  com.sirius.game.proto.SCLoginResultOrBuilder getScLoginResultOrBuilder();

  /**
   * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
   * @return Whether the csSendMessage field is set.
   */
  boolean hasCsSendMessage();
  /**
   * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
   * @return The csSendMessage.
   */
  com.sirius.game.proto.CSSendMessage getCsSendMessage();
  /**
   * <code>.com.sirius.game.proto.CSSendMessage cs_send_message = 2001;</code>
   */
  com.sirius.game.proto.CSSendMessageOrBuilder getCsSendMessageOrBuilder();

  /**
   * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
   * @return Whether the scReceiveMessage field is set.
   */
  boolean hasScReceiveMessage();
  /**
   * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
   * @return The scReceiveMessage.
   */
  com.sirius.game.proto.SCReceiveMessage getScReceiveMessage();
  /**
   * <code>.com.sirius.game.proto.SCReceiveMessage sc_receive_message = 2002;</code>
   */
  com.sirius.game.proto.SCReceiveMessageOrBuilder getScReceiveMessageOrBuilder();

  com.sirius.game.proto.GameMessage.PayloadCase getPayloadCase();
}
