// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

/**
 * <pre>
 * 统一消息类型
 * </pre>
 *
 * Protobuf type {@code com.sirius.game.proto.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.sirius.game.proto.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sirius.game.proto.ChatProtos.internal_static_com_sirius_game_proto_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sirius.game.proto.ChatProtos.internal_static_com_sirius_game_proto_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sirius.game.proto.Message.class, com.sirius.game.proto.Message.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SEND_REQUEST(2),
    RECEIVE_NOTIFICATION(3),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 2: return SEND_REQUEST;
        case 3: return RECEIVE_NOTIFICATION;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <pre>
   * 消息类型标识符
   * </pre>
   *
   * <code>.com.sirius.game.proto.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 消息类型标识符
   * </pre>
   *
   * <code>.com.sirius.game.proto.MessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.sirius.game.proto.MessageType getType() {
    com.sirius.game.proto.MessageType result = com.sirius.game.proto.MessageType.forNumber(type_);
    return result == null ? com.sirius.game.proto.MessageType.UNRECOGNIZED : result;
  }

  public static final int SEND_REQUEST_FIELD_NUMBER = 2;
  /**
   * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
   * @return Whether the sendRequest field is set.
   */
  @java.lang.Override
  public boolean hasSendRequest() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
   * @return The sendRequest.
   */
  @java.lang.Override
  public com.sirius.game.proto.SendMessageRequest getSendRequest() {
    if (payloadCase_ == 2) {
       return (com.sirius.game.proto.SendMessageRequest) payload_;
    }
    return com.sirius.game.proto.SendMessageRequest.getDefaultInstance();
  }
  /**
   * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
   */
  @java.lang.Override
  public com.sirius.game.proto.SendMessageRequestOrBuilder getSendRequestOrBuilder() {
    if (payloadCase_ == 2) {
       return (com.sirius.game.proto.SendMessageRequest) payload_;
    }
    return com.sirius.game.proto.SendMessageRequest.getDefaultInstance();
  }

  public static final int RECEIVE_NOTIFICATION_FIELD_NUMBER = 3;
  /**
   * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
   * @return Whether the receiveNotification field is set.
   */
  @java.lang.Override
  public boolean hasReceiveNotification() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
   * @return The receiveNotification.
   */
  @java.lang.Override
  public com.sirius.game.proto.ReceiveMessageNotification getReceiveNotification() {
    if (payloadCase_ == 3) {
       return (com.sirius.game.proto.ReceiveMessageNotification) payload_;
    }
    return com.sirius.game.proto.ReceiveMessageNotification.getDefaultInstance();
  }
  /**
   * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
   */
  @java.lang.Override
  public com.sirius.game.proto.ReceiveMessageNotificationOrBuilder getReceiveNotificationOrBuilder() {
    if (payloadCase_ == 3) {
       return (com.sirius.game.proto.ReceiveMessageNotification) payload_;
    }
    return com.sirius.game.proto.ReceiveMessageNotification.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.sirius.game.proto.MessageType.UNKNOWN.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (payloadCase_ == 2) {
      output.writeMessage(2, (com.sirius.game.proto.SendMessageRequest) payload_);
    }
    if (payloadCase_ == 3) {
      output.writeMessage(3, (com.sirius.game.proto.ReceiveMessageNotification) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.sirius.game.proto.MessageType.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (payloadCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.sirius.game.proto.SendMessageRequest) payload_);
    }
    if (payloadCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.sirius.game.proto.ReceiveMessageNotification) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sirius.game.proto.Message)) {
      return super.equals(obj);
    }
    com.sirius.game.proto.Message other = (com.sirius.game.proto.Message) obj;

    if (type_ != other.type_) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 2:
        if (!getSendRequest()
            .equals(other.getSendRequest())) return false;
        break;
      case 3:
        if (!getReceiveNotification()
            .equals(other.getReceiveNotification())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    switch (payloadCase_) {
      case 2:
        hash = (37 * hash) + SEND_REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getSendRequest().hashCode();
        break;
      case 3:
        hash = (37 * hash) + RECEIVE_NOTIFICATION_FIELD_NUMBER;
        hash = (53 * hash) + getReceiveNotification().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sirius.game.proto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sirius.game.proto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sirius.game.proto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sirius.game.proto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sirius.game.proto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sirius.game.proto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sirius.game.proto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sirius.game.proto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.sirius.game.proto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.sirius.game.proto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sirius.game.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sirius.game.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sirius.game.proto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 统一消息类型
   * </pre>
   *
   * Protobuf type {@code com.sirius.game.proto.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.sirius.game.proto.Message)
      com.sirius.game.proto.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sirius.game.proto.ChatProtos.internal_static_com_sirius_game_proto_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sirius.game.proto.ChatProtos.internal_static_com_sirius_game_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sirius.game.proto.Message.class, com.sirius.game.proto.Message.Builder.class);
    }

    // Construct using com.sirius.game.proto.Message.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      if (sendRequestBuilder_ != null) {
        sendRequestBuilder_.clear();
      }
      if (receiveNotificationBuilder_ != null) {
        receiveNotificationBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sirius.game.proto.ChatProtos.internal_static_com_sirius_game_proto_Message_descriptor;
    }

    @java.lang.Override
    public com.sirius.game.proto.Message getDefaultInstanceForType() {
      return com.sirius.game.proto.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.sirius.game.proto.Message build() {
      com.sirius.game.proto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sirius.game.proto.Message buildPartial() {
      com.sirius.game.proto.Message result = new com.sirius.game.proto.Message(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.sirius.game.proto.Message result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
    }

    private void buildPartialOneofs(com.sirius.game.proto.Message result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 2 &&
          sendRequestBuilder_ != null) {
        result.payload_ = sendRequestBuilder_.build();
      }
      if (payloadCase_ == 3 &&
          receiveNotificationBuilder_ != null) {
        result.payload_ = receiveNotificationBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sirius.game.proto.Message) {
        return mergeFrom((com.sirius.game.proto.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sirius.game.proto.Message other) {
      if (other == com.sirius.game.proto.Message.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      switch (other.getPayloadCase()) {
        case SEND_REQUEST: {
          mergeSendRequest(other.getSendRequest());
          break;
        }
        case RECEIVE_NOTIFICATION: {
          mergeReceiveNotification(other.getReceiveNotification());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getSendRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getReceiveNotificationFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.sirius.game.proto.MessageType getType() {
      com.sirius.game.proto.MessageType result = com.sirius.game.proto.MessageType.forNumber(type_);
      return result == null ? com.sirius.game.proto.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.sirius.game.proto.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型标识符
     * </pre>
     *
     * <code>.com.sirius.game.proto.MessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.SendMessageRequest, com.sirius.game.proto.SendMessageRequest.Builder, com.sirius.game.proto.SendMessageRequestOrBuilder> sendRequestBuilder_;
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     * @return Whether the sendRequest field is set.
     */
    @java.lang.Override
    public boolean hasSendRequest() {
      return payloadCase_ == 2;
    }
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     * @return The sendRequest.
     */
    @java.lang.Override
    public com.sirius.game.proto.SendMessageRequest getSendRequest() {
      if (sendRequestBuilder_ == null) {
        if (payloadCase_ == 2) {
          return (com.sirius.game.proto.SendMessageRequest) payload_;
        }
        return com.sirius.game.proto.SendMessageRequest.getDefaultInstance();
      } else {
        if (payloadCase_ == 2) {
          return sendRequestBuilder_.getMessage();
        }
        return com.sirius.game.proto.SendMessageRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     */
    public Builder setSendRequest(com.sirius.game.proto.SendMessageRequest value) {
      if (sendRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        sendRequestBuilder_.setMessage(value);
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     */
    public Builder setSendRequest(
        com.sirius.game.proto.SendMessageRequest.Builder builderForValue) {
      if (sendRequestBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        sendRequestBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     */
    public Builder mergeSendRequest(com.sirius.game.proto.SendMessageRequest value) {
      if (sendRequestBuilder_ == null) {
        if (payloadCase_ == 2 &&
            payload_ != com.sirius.game.proto.SendMessageRequest.getDefaultInstance()) {
          payload_ = com.sirius.game.proto.SendMessageRequest.newBuilder((com.sirius.game.proto.SendMessageRequest) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 2) {
          sendRequestBuilder_.mergeFrom(value);
        } else {
          sendRequestBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 2;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     */
    public Builder clearSendRequest() {
      if (sendRequestBuilder_ == null) {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 2) {
          payloadCase_ = 0;
          payload_ = null;
        }
        sendRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     */
    public com.sirius.game.proto.SendMessageRequest.Builder getSendRequestBuilder() {
      return getSendRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     */
    @java.lang.Override
    public com.sirius.game.proto.SendMessageRequestOrBuilder getSendRequestOrBuilder() {
      if ((payloadCase_ == 2) && (sendRequestBuilder_ != null)) {
        return sendRequestBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 2) {
          return (com.sirius.game.proto.SendMessageRequest) payload_;
        }
        return com.sirius.game.proto.SendMessageRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.SendMessageRequest, com.sirius.game.proto.SendMessageRequest.Builder, com.sirius.game.proto.SendMessageRequestOrBuilder> 
        getSendRequestFieldBuilder() {
      if (sendRequestBuilder_ == null) {
        if (!(payloadCase_ == 2)) {
          payload_ = com.sirius.game.proto.SendMessageRequest.getDefaultInstance();
        }
        sendRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sirius.game.proto.SendMessageRequest, com.sirius.game.proto.SendMessageRequest.Builder, com.sirius.game.proto.SendMessageRequestOrBuilder>(
                (com.sirius.game.proto.SendMessageRequest) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 2;
      onChanged();
      return sendRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.ReceiveMessageNotification, com.sirius.game.proto.ReceiveMessageNotification.Builder, com.sirius.game.proto.ReceiveMessageNotificationOrBuilder> receiveNotificationBuilder_;
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     * @return Whether the receiveNotification field is set.
     */
    @java.lang.Override
    public boolean hasReceiveNotification() {
      return payloadCase_ == 3;
    }
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     * @return The receiveNotification.
     */
    @java.lang.Override
    public com.sirius.game.proto.ReceiveMessageNotification getReceiveNotification() {
      if (receiveNotificationBuilder_ == null) {
        if (payloadCase_ == 3) {
          return (com.sirius.game.proto.ReceiveMessageNotification) payload_;
        }
        return com.sirius.game.proto.ReceiveMessageNotification.getDefaultInstance();
      } else {
        if (payloadCase_ == 3) {
          return receiveNotificationBuilder_.getMessage();
        }
        return com.sirius.game.proto.ReceiveMessageNotification.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     */
    public Builder setReceiveNotification(com.sirius.game.proto.ReceiveMessageNotification value) {
      if (receiveNotificationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        receiveNotificationBuilder_.setMessage(value);
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     */
    public Builder setReceiveNotification(
        com.sirius.game.proto.ReceiveMessageNotification.Builder builderForValue) {
      if (receiveNotificationBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        receiveNotificationBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     */
    public Builder mergeReceiveNotification(com.sirius.game.proto.ReceiveMessageNotification value) {
      if (receiveNotificationBuilder_ == null) {
        if (payloadCase_ == 3 &&
            payload_ != com.sirius.game.proto.ReceiveMessageNotification.getDefaultInstance()) {
          payload_ = com.sirius.game.proto.ReceiveMessageNotification.newBuilder((com.sirius.game.proto.ReceiveMessageNotification) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 3) {
          receiveNotificationBuilder_.mergeFrom(value);
        } else {
          receiveNotificationBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 3;
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     */
    public Builder clearReceiveNotification() {
      if (receiveNotificationBuilder_ == null) {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 3) {
          payloadCase_ = 0;
          payload_ = null;
        }
        receiveNotificationBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     */
    public com.sirius.game.proto.ReceiveMessageNotification.Builder getReceiveNotificationBuilder() {
      return getReceiveNotificationFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     */
    @java.lang.Override
    public com.sirius.game.proto.ReceiveMessageNotificationOrBuilder getReceiveNotificationOrBuilder() {
      if ((payloadCase_ == 3) && (receiveNotificationBuilder_ != null)) {
        return receiveNotificationBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 3) {
          return (com.sirius.game.proto.ReceiveMessageNotification) payload_;
        }
        return com.sirius.game.proto.ReceiveMessageNotification.getDefaultInstance();
      }
    }
    /**
     * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.sirius.game.proto.ReceiveMessageNotification, com.sirius.game.proto.ReceiveMessageNotification.Builder, com.sirius.game.proto.ReceiveMessageNotificationOrBuilder> 
        getReceiveNotificationFieldBuilder() {
      if (receiveNotificationBuilder_ == null) {
        if (!(payloadCase_ == 3)) {
          payload_ = com.sirius.game.proto.ReceiveMessageNotification.getDefaultInstance();
        }
        receiveNotificationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.sirius.game.proto.ReceiveMessageNotification, com.sirius.game.proto.ReceiveMessageNotification.Builder, com.sirius.game.proto.ReceiveMessageNotificationOrBuilder>(
                (com.sirius.game.proto.ReceiveMessageNotification) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 3;
      onChanged();
      return receiveNotificationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.sirius.game.proto.Message)
  }

  // @@protoc_insertion_point(class_scope:com.sirius.game.proto.Message)
  private static final com.sirius.game.proto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sirius.game.proto.Message();
  }

  public static com.sirius.game.proto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sirius.game.proto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

