// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

/**
 * <pre>
 * 消息类型枚举
 * </pre>
 *
 * Protobuf enum {@code com.sirius.game.proto.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>CS_LOGIN = 1001;</code>
   */
  CS_LOGIN(1001),
  /**
   * <code>SC_LOGIN_RESULT = 1002;</code>
   */
  SC_LOGIN_RESULT(1002),
  /**
   * <code>CS_SEND_MESSAGE = 2001;</code>
   */
  CS_SEND_MESSAGE(2001),
  /**
   * <code>SC_RECEIVE_MESSAGE = 2002;</code>
   */
  SC_RECEIVE_MESSAGE(2002),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>CS_LOGIN = 1001;</code>
   */
  public static final int CS_LOGIN_VALUE = 1001;
  /**
   * <code>SC_LOGIN_RESULT = 1002;</code>
   */
  public static final int SC_LOGIN_RESULT_VALUE = 1002;
  /**
   * <code>CS_SEND_MESSAGE = 2001;</code>
   */
  public static final int CS_SEND_MESSAGE_VALUE = 2001;
  /**
   * <code>SC_RECEIVE_MESSAGE = 2002;</code>
   */
  public static final int SC_RECEIVE_MESSAGE_VALUE = 2002;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1001: return CS_LOGIN;
      case 1002: return SC_LOGIN_RESULT;
      case 2001: return CS_SEND_MESSAGE;
      case 2002: return SC_RECEIVE_MESSAGE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.sirius.game.proto.GameProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.sirius.game.proto.MessageType)
}

