// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sirius.game.proto.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息类型标识符
   * </pre>
   *
   * <code>.com.sirius.game.proto.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * 消息类型标识符
   * </pre>
   *
   * <code>.com.sirius.game.proto.MessageType type = 1;</code>
   * @return The type.
   */
  com.sirius.game.proto.MessageType getType();

  /**
   * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
   * @return Whether the sendRequest field is set.
   */
  boolean hasSendRequest();
  /**
   * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
   * @return The sendRequest.
   */
  com.sirius.game.proto.SendMessageRequest getSendRequest();
  /**
   * <code>.com.sirius.game.proto.SendMessageRequest send_request = 2;</code>
   */
  com.sirius.game.proto.SendMessageRequestOrBuilder getSendRequestOrBuilder();

  /**
   * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
   * @return Whether the receiveNotification field is set.
   */
  boolean hasReceiveNotification();
  /**
   * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
   * @return The receiveNotification.
   */
  com.sirius.game.proto.ReceiveMessageNotification getReceiveNotification();
  /**
   * <code>.com.sirius.game.proto.ReceiveMessageNotification receive_notification = 3;</code>
   */
  com.sirius.game.proto.ReceiveMessageNotificationOrBuilder getReceiveNotificationOrBuilder();

  com.sirius.game.proto.Message.PayloadCase getPayloadCase();
}
