// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

public interface ReceiveMessageNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sirius.game.proto.ReceiveMessageNotification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>string from = 1;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>string from = 1;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <pre>
   * 接收者ID
   * </pre>
   *
   * <code>string to = 2;</code>
   * @return The to.
   */
  java.lang.String getTo();
  /**
   * <pre>
   * 接收者ID
   * </pre>
   *
   * <code>string to = 2;</code>
   * @return The bytes for to.
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 消息ID
   * </pre>
   *
   * <code>string message_id = 5;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <pre>
   * 消息ID
   * </pre>
   *
   * <code>string message_id = 5;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();
}
