// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

// Protobuf Java Version: 3.25.1
package com.sirius.game.proto;

public interface SCLoginResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.sirius.game.proto.SCLoginResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 登录是否成功
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * 结果消息（如错误信息）
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 结果消息（如错误信息）
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * 用户ID（登录成功时返回）
   * </pre>
   *
   * <code>string user_id = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * 用户ID（登录成功时返回）
   * </pre>
   *
   * <code>string user_id = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * 会话令牌（登录成功时返回）
   * </pre>
   *
   * <code>string session_token = 4;</code>
   * @return The sessionToken.
   */
  java.lang.String getSessionToken();
  /**
   * <pre>
   * 会话令牌（登录成功时返回）
   * </pre>
   *
   * <code>string session_token = 4;</code>
   * @return The bytes for sessionToken.
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();

  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
